/* Applies pending SQL migrations from ./drizzle (generated by drizzle-kit). Retries while MySQL is starting. */
import path from 'node:path'
import { migrate } from 'drizzle-orm/mysql2/migrator'
import { db, pool } from './db/client'

async function main() {
  const folder = path.resolve(__dirname, '..', 'drizzle')
  for (let attempt = 1; ; attempt++) {
    try {
      await pool.query('SELECT 1')
      break
    } catch (e) {
      if (attempt >= 30) throw e
      console.log(`waiting for MySQL (${attempt})…`)
      await new Promise((r) => setTimeout(r, 2000))
    }
  }
  await migrate(db, { migrationsFolder: folder })
  console.log('migrations applied')
}

main().catch((e) => { console.error(e); process.exit(1) }).finally(() => pool.end())
